project:
  type: website

website:
  title: "The Indo-European Similarities Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Germanic vs. Romance.qmd
      - Celtic vs. Indic.qmd
      - Balto-Slavic.qmd
      - about.qmd
      - Source.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



